### ISSUE TITLE
Wireframe Login and Register

### ISSUE THREAD

**Issue by reamejosee** [Code0fDuty/Code0fDutyProj#14]

**Comment by lalay29** [comment]
[Wireframe_LOGIN.pdf](https://github.com/Code0fDuty/Team7_BSIS_3AB/files/7697320/Wireframe_LOGIN.pdf)
[Wireframe_SIgnUP.pdf](https://github.com/Code0fDuty/Team7_BSIS_3AB/files/7697329/Wireframe_SIgnUP.pdf)
